# Generated by Django 4.2.8 on 2023-12-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="addJobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("openings", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("skills_required", models.CharField(max_length=100)),
            ],
        ),
    ]
